INSERT INTO T_TOURNAMENT(ID, PLACE, `DATE`, ORGANIZER)
VALUES (1, 'Wrocław, ul.Grunwaldzka 64a', '2021-01-29 16:00:00', 'Krzysztof Gwóźdź');

INSERT INTO T_MATCH(ID, FINAL_RESULT, SET_RESULTS, TOURNAMENT_ID)
VALUES (1, '2:0', '11:3;11:6', 1);
INSERT INTO T_MATCH(ID, FINAL_RESULT, SET_RESULTS, TOURNAMENT_ID)
VALUES (2, '2:1', '11:3;1:11;13:11', 1);
INSERT INTO T_MATCH(ID, FINAL_RESULT, SET_RESULTS, TOURNAMENT_ID)
VALUES (3, '1:2', '3:11;11:3;9:11', 1);

INSERT INTO T_USER(ID, EMAIL, PASSWORD, NAME, LAST_NAME, ROLE, CREATION_DATE)
VALUES (1, 'as@wp.pl', 'asadbadasd', 'user_name', 'user_last_name', 'user', NOW());

INSERT INTO t_user_tournament(USER_ID, TOURNAMENT_ID) VALUES (1, 1);