CREATE TABLE T_MATCH
(
    ID               int(10)     NOT NULL AUTO_INCREMENT,
    FIRST_PLAYER_ID  int(10)     NOT NULL,
    SECOND_PLAYER_ID int(10)     NOT NULL,
    FINAL_RESULT     varchar(3)  NOT NULL,
    SET_RESULTS      varchar(50) NOT NULL,
    TOURNAMENT_ID    int(10)     NOT NULL,
    PRIMARY KEY (ID)
);
CREATE TABLE T_TOURNAMENT
(
    ID          int(10)     NOT NULL AUTO_INCREMENT,
    NAME        varchar(255),
    CITY        varchar(80) NOT NULL,
    STREET      varchar(80) NOT NULL,
    `DATE`      datetime    NOT NULL,
    ORGANIZER   varchar(80) NOT NULL,
    DESCRIPTION varchar(255),
    PRIMARY KEY (ID)
);

CREATE TABLE T_USER
(
    ID            int(10)      NOT NULL AUTO_INCREMENT,
    EMAIL         varchar(50)  NOT NULL,
    PASSWORD      varchar(255) NOT NULL,
    NAME          varchar(50)  NOT NULL,
    LAST_NAME     varchar(50)  NOT NULL,
    RATING        float,
    ROLE          varchar(30)  NOT NULL,
    CREATION_DATE datetime     NULL,
    PRIMARY KEY (ID)
);
CREATE TABLE T_USER_TOURNAMENT
(
    USER_ID       int(10) NOT NULL,
    TOURNAMENT_ID int(10) NOT NULL,
    PRIMARY KEY (USER_ID, TOURNAMENT_ID)
);
ALTER TABLE T_MATCH
    ADD CONSTRAINT FKT_MATCH81441 FOREIGN KEY (SECOND_PLAYER_ID) REFERENCES T_USER (ID);
ALTER TABLE T_MATCH
    ADD CONSTRAINT FKT_MATCH698110 FOREIGN KEY (FIRST_PLAYER_ID) REFERENCES T_USER (ID);
ALTER TABLE T_MATCH
    ADD CONSTRAINT FKT_MATCH62589 FOREIGN KEY (TOURNAMENT_ID) REFERENCES T_TOURNAMENT (ID);
ALTER TABLE T_USER_TOURNAMENT
    ADD CONSTRAINT FKT_USER_TOU412598 FOREIGN KEY (TOURNAMENT_ID) REFERENCES T_TOURNAMENT (ID);
ALTER TABLE T_USER_TOURNAMENT
    ADD CONSTRAINT FKT_USER_TOU615421 FOREIGN KEY (USER_ID) REFERENCES T_USER (ID);